//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazingChat.Server.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Sex { get; set; }
        public string Avatar { get; set; }
        public string Remark { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public bool IsValid { get; set; }
    }
}
